### ISSUE TITLE
rep-gtk fails to build on NixOS-Darwin

### ISSUE THREAD

**Issue by AndersonTorres** [SawfishWM/rep-gtk#4]
According to our CI, it fails in finding gdkx.h file.

https://hydra.nixos.org/log/8iyw6bq5ckpk5v6zbhszlgaf8adxwpm4-rep-gtk-0.90.8.3.drv

> libtool: compile:  clang -c -DHAVE_CONFIG_H -I. -g -O2 -I/nix/store/yhq8cx9b93r9ji1mfvyrvh6y8vplsivj-glib-2.76.2-dev/include/glib-2.0 -I/nix/store/3gaqwxg3wc4hvm6yhsr6wmqfd8p5fd3y-glib-2.76.2/lib/glib-2.0/include -I/nix/store/vi255nf9z9fj6gq2lysk4s1nkdsranaz-gtk+-2.24.33-dev/include/gtk-2.0 -I/nix/store/bi1840hdgaq1l6dx3l73ggmi7dvvf5yv-gtk+-2.24.33/lib/gtk-2.0/include -I/nix/store/yhq8cx9b93r9ji1mfvyrvh6y8vplsivj-glib-2.76.2-dev/include -I/nix/store/yhq8cx9b93r9ji1mfvyrvh6y8vplsivj-glib-2.76.2-dev/include/glib-2.0 -I/nix/store/3gaqwxg3wc4hvm6yhsr6wmqfd8p5fd3y-glib-2.76.2/lib/glib-2.0/include -I/nix/store/gb1ml8pakskmqnmxmaa89msbni56hmpa-cairo-1.16.0-dev/include/cairo -I/nix/store/dq7wf53wys3f9nvmffbqi5al2rrbzzap-freetype-2.13.0-dev/include/freetype2 -I/nix/store/dq7wf53wys3f9nvmffbqi5al2rrbzzap-freetype-2.13.0-dev/include -I/nix/store/2yqd20gdd5rbi5svfss1n1h0yacvrf5q-pango-1.50.14-dev/include/pango-1.0 -I/nix/store/ah8yvj3zyppjmrncv1xqi8jgf0c01v7s-harfbuzz-7.2.0-dev/include/harfbuzz -I/nix/store/qkmldwqh5gmz31nvnbxp8blsx7wf161w-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 -I/nix/store/y7pa00ij59q0mhprlkk9l5mi2vz0jg8c-at-spi2-core-2.48.0-dev/include/atk-1.0 -I/nix/store/78hyg0n2fbhjbkk3vi7p0fjrd0daai5l-librep-0.92.7/include/ -I/nix/store/78hyg0n2fbhjbkk3vi7p0fjrd0daai5l-librep-0.92.7/lib/rep/ -I/nix/store/yhq8cx9b93r9ji1mfvyrvh6y8vplsivj-glib-2.76.2-dev/include -I/nix/store/yhq8cx9b93r9ji1mfvyrvh6y8vplsivj-glib-2.76.2-dev/include/glib-2.0 -I/nix/store/3gaqwxg3wc4hvm6yhsr6wmqfd8p5fd3y-glib-2.76.2/lib/glib-2.0/include -I/nix/store/qkmldwqh5gmz31nvnbxp8blsx7wf161w-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 rep-gtk.c  -fno-common -DPIC -o .libs/rep-gtk.o
> rep-gtk.c:26:10: fatal error: 'gdk/gdkx.h' file not found
> #include <gdk/gdkx.h>

**Comment by AndersonTorres** [comment]
Here are the full logs:

https://hydra.nixos.org/build/219940787
https://hydra.nixos.org/build/219910896

Also, those are Darwin Apple machines.

**Comment by Nanolx** [comment]
Is your GTK+2 built with X11 support?

**Comment by AndersonTorres** [comment]
No, it isn't. Or, more precisely, its `gdkTarget` is set to Quartz when built on Darwin.
(It can be overrided, tho.)
